spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=IrCdqGdFZXsecwnSoSRSlAoMhseUMTFg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

ticketmaster.api.key=${TICKETMASTER_API_KEY}
openweather.api.key=${OPENWEATHER_API_KEY}
jwt.secret=${JWT_SECRET}

